name: Node.js

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_unicode_ci'
          mysql version: '5.7'
          mysql database: 'udon'
          mysql user: 'udon'
          mysql password: 'udon'

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> ~/.npmrc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm migrate
      - run: npm test
